language: perl
perl:
- '5.20'
- '5.10'
addons:
- postgresql: "9.4"
services:
- mysql
- postgresql
before_script:
- mysql -e "create database seccubus_create"
- mysql -e "create database seccubus_upgrade"
- mysql -e "create database seccubus"
- createdb travis
- cpanm DBI DBD::mysql DBD::Pg
sudo: false
notifications:
  slack:
    secure: XWiapPB78I09dke7/JTe22nmOVEuWbQl183iCP/8ML3MFAUZ1SnckMSKyqVMxtYZpFrBGHtY3xFjikG1148KS74/HVW6WREV4agDqHRI5FN8z2LQjgs1cD2svbK2uVxYN+a1oubX+mdZG2TTXfejN23P+HAwMo/8rNUcx+Qfb7M=
